<?php if ($block->getTotals()) : ?>
    <?php $_colspan = 3; ?>
    <?php echo /* @noEscape */ $block->renderTotals(null, $_colspan) ?>
    <?php echo /* @noEscape */ $block->renderTotals('footer', $_colspan) ?>
    <?php if ($block->needDisplayBaseGrandtotal()) : ?>
    <tr class="totals charge">
        <th class="mark" colspan="<?php echo /* @noEscape */ $_colspan ?>" scope="row">
            <?php echo $block->escapeHtml(__('Your credit card will be charged for')) ?>
        </th>
        <td class="amount" data-th="<?php echo $block->escapeHtmlAttr(__('Your credit card will be charged for')) ?>">
            <?php echo /* @noEscape */ $block->displayBaseGrandtotal() ?>
        </td>
    </tr>
    <?php endif?>
<?php endif; ?>