<style>
.order-payment-method-title, .order-payment-currency { display:none; }
</style>

<<?php echo $block->escapeHtml($block->getData('elementType')); ?> 
    tx-id="<?php echo $block->escapeHtml($block->getPayment()->getAdditionalInformation('transaction_id')); ?>" 
    date="<?php echo $block->escapeHtml($block->getCreatedAtFormatted()); ?>"
></<?php echo $block->escapeHtml($block->getData('elementType')); ?>>