<?php
/**
 * @see \Netzkollektiv\EasyCredit\Block\Adminhtml\System\Config\ApiWizard
 * @var \Netzkollektiv\EasyCredit\Block\Adminhtml\System\Config\ApiWizard $block
 */
?>
<div class="pp-buttons-container">
    <div dir="ltr" style="text-align: left;" trbidi="on">
        <a id="easycredit-verify-credentials"
            class="action-default"
            href="#">
            <?php echo $block->escapeHtml($block->getButtonLabel()); ?>
        </a>
    </div>
</div>

<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/alert",
        'mage/storage',
        "mage/translate",
        "domReady!"
    ], function ($, alertModal, storage) {


        function easyCreditVerifyCredentials () {
            var apiKeySelector = "<?php echo $block->escapeHtml($block->getApiKeySelector()); ?>",
                apiTokenSelector = "<?php echo $block->escapeHtml($block->getApiTokenSelector()); ?>",
                apiSignatureSelector = "<?php echo $block->escapeHtml($block->getApiSignatureSelector()); ?>",
                apiKey= $('input[data-ui-id="' + apiKeySelector + '"]').val(),
                apiToken = $('input[data-ui-id="' + apiTokenSelector + '"]').val(),
                apiSignature = $('input[data-ui-id="' + apiSignatureSelector + '"]').val(),
                serviceUrl = "<?php echo $block->escapeHtml($block->getServiceUrl()); ?>";

            if (apiKey.length === 0 || apiToken.length === 0) {
                alertModal({content: '<?php echo __("Please insert Api Key and Token") ?>'});
                return;
            }

            
            return storage['<?php echo $block->escapeHtml($block->getServiceMethod()); ?>'](
                serviceUrl + '?apiKey=' + encodeURIComponent(apiKey) + 
                    '&apiToken=' + encodeURIComponent(apiToken) + 
                    '&apiSignature=' + encodeURIComponent(apiSignature)
            ).done(function (response) {
                alertModal({
                    content: '<?php echo __('Credentials are valid. After saving the configuration the extension is ready for operation.') ?>'
                });
            }).fail(function (response) {
                var message = response.responseJSON.message;
                alertModal({content: $.mage.__(message)});
            });
        }

        $("#easycredit-verify-credentials").click(function() {
            $(this).attr('disabled', true);
            easyCreditVerifyCredentials().always(function(){
                $(this).attr('disabled', false);
            }.bind(this));
            return false;
        });
    });
</script>
