<?php
/**
 * @see \Netzkollektiv\EasyCredit\Block\Adminhtml\System\Config\BillPaymentIntro
 * @var \Netzkollektiv\EasyCredit\Block\Adminhtml\System\Config\BillPaymentIntro $block
 */
?>
<div class="sw-card" id="ecbill">
    <div class="sw-card__content">
        <div class="easycredit-marketing card intro-2024 bill">
            <div class="easycredit-marketing__grid grid-50-50">
                <div class="easycredit-marketing__image bg fill aspect-36-2"></div>

                <div class="easycredit-marketing__content">
                    <span class="badge">Neu</span>
                    <h2><?= __('easyCredit-Rechnung - the ideal addition to installment purchase') ?></h2>
                    <p><?= __('With easyCredit, you can now offer your customers the option of invoice purchase in addition to the classic installment purchase. The payment term is <strong>30 days in the future</strong>.') ?></p>
                    <a
                        class="btn btn-secondary"
                        id="easycredit-activate-invoice-button-active"
                        href="#payment_us_easycredit_easycredit_rechnung"
                    >
                        <?= __('Activate now') ?>
                    </a>
                    <a
                        class="btn btn-secondary"
                        id="easycredit-activate-invoice-button-inactive"
                        href="https://partner.easycredit-ratenkauf.de/portal"
                        target="_blank"
                    >
                        <?= __('Unlock now') ?>
                    </a>
                    <a
                        class="btn btn-link"
                        href="https://www.easycredit-ratenkauf.de/produkt/"
                        target="_blank"
                    >
                        <?= __('Learn more') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/alert",
        'mage/storage',
        "mage/translate",
        "domReady!"
    ], function ($, alertModal, storage) {

        function getPaymentMethodStatus () {
            var installmentPaymentStatus = '<?php echo $block->getPaymentMethodStatus("easycredit_ratenkauf"); ?>';
            var billPaymentStatus = '<?php echo $block->getPaymentMethodStatus("easycredit_rechnung"); ?>';

            elBillPayment = $('#ecbill .bill');

            installmentPaymentStatus === '0' ? elBillPayment[0].classList.add('easycredit_ratenkauf-not-active') : null;
            billPaymentStatus === '0' ? elBillPayment[0].classList.add('easycredit_rechnung-not-active') : null;
        }

        function fetchWebshopInfo () {
            apiKey = '<?php echo $block->getApiKey(); ?>';
            // console.log(apiKey);

            if (apiKey.length === 0) {
                return;
            }

            const url = 'https://ratenkauf.easycredit.de/api/payment/v3/webshop/' + apiKey;

            return fetch(url).then((response) => {
                if (!response.ok) { 
                    return Promise.reject(response); 
                }
                return response.json();
            }).then((data) => {
                return data;
            }).catch((error) => {
                console.error('Error fetching webshop info:', error);
            });
        }

        $( document ).ready( function() {
            getPaymentMethodStatus();

            fetchWebshopInfo().then((data) => {
                elBillPayment = $('#ecbill .bill');

                if ( data.billPaymentActive === true ) {
                    $('#easycredit-activate-invoice-button-inactive').remove();
                } else {
                    $('#easycredit-activate-invoice-button-active').remove();
                    elBillPayment[0].classList.add('easycredit_rechnung-not-allowed');
                }
            });
        });
    });
</script>
