<div class="easycredit-marketing clickandcollect">
    <div class="easycredit-marketing__grid">
        <div class="easycredit-marketing__content">
            <p>
                <?= __('You want to use Click&Collect for easyCredit-Ratenkauf? Nothing could be simpler! To be able to use the feature, you need an additional supplementary agreement to your factoring contract. To do so, simply contact your key account manager or ask him via our <a href="https://www.easycredit-ratenkauf.de/click-und-collect/" target="_blank">Click&Collect form</a>.') ?>
            </p>
            <p>
                <?= __('It is important for you that when using Click&Collect you must ensure that the purchased product is handed over exclusively to the contractual partner. The responsibility for the correct handover lies with you as the merchant.') ?>
            </p>
            <p>
                <?= __('Please set the shipping method with which you offer Click&Collect in the following:') ?>
            </p>
        </div>
        <div class="easycredit-marketing__image bg">
            <div class="img"></div>
        </div>
    </div>
</div>

<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/alert",
        'mage/storage',
        "mage/translate",
        "domReady!"
    ], function ($, alertModal, storage) {

        $( document ).ready( function() {
            el = $('#row_payment_us_easycredit_clickandcollect_click_and_collect td.value');
            el.attr('colspan',3);
        });
    });
</script>
