<div class="easycredit-marketing__grid">
    <div class="sw-card">
        <div class="sw-card__content">
            <div class="easycredit-marketing card intro-2024">
                <div class="easycredit-marketing__grid">
                    <div class="easycredit-marketing__content">
                        <h2><?= __('The simplest invoice and installment purchase in Germany.') ?></h2>
                        <p><?= __('We are delighted that you have decided in favour of easyCredit, the perfect payment method for your online shop.') ?></p>
                        <div class="mb-1">
                            <a
                                class="btn btn-secondary"
                                href="https://netzkollektiv.com/docs/easycredit-magento2"
                                target="_blank"
                            >
                                <?= __('Documentation') ?>
                            </a>
                            <a
                                class="btn btn-secondary"
                                href="https://easycredit-demo.netzkollektiv.com/"
                                target="_blank"
                            >
                                <?= __('Demo shop') ?>
                            </a>
                        </div>
                        <a href="https://partner.easycredit-ratenkauf.de/registrierung/firmendaten" target="_blank" class="not-decorated"><?= __('Register as a trader') ?></a>
                    </div>

                    <div class="easycredit-marketing__image bg fill aspect-2-3">
                        <div class="img"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="sw-card dimmed">
        <div class="sw-card__content">
            <div class="easycredit-marketing card intro-2024">
                <div class="easycredit-marketing__content">
                    <h2><?= __('Do you have any questions? We are here to help.') ?></h2>
                    <p><?= __('We are here for you from Monday to Friday from 8:00 to 18:00.') ?></p>
                    <ul>
                        <li><a href="https://www.easycredit-ratenkauf.de/kontakt/" target="_blank"><?= __('Frequently asked questions (FAQ)') ?></a></li>
                        <li><a href="tel:091153902726" target="_blank"><?= __('Give us a call: +49 (0)911 5390-2726') ?></a></li>
                        <li><a href="https://www.easycredit-ratenkauf.de/kontakt/#b064f73c4cdfc080a73b69ea0125da53" target="_blank"><?= __('Contact form') ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
