<div class="easycredit-marketing">
    <div class="easycredit-marketing__grid bar">
        <div class="easycredit-marketing__content">
            <p><?= __('The bar component can be displayed at the top of the screen and promotes the hire purchase with short slogans. The slogans are predefined and cannot be customised.') ?></p>
        </div>
        <div class="easycredit-marketing__image bg">
            <div class="img"></div>
        </div>
    </div>
</div>

<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/alert",
        'mage/storage',
        "mage/translate",
        "domReady!"
    ], function ($, alertModal, storage) {

        $( document ).ready( function() {
            el = $('#row_payment_us_easycredit_marketing_bar_marketing_bar td.value');
            el.attr('colspan',3);
        });
    });
</script>
