<div class="easycredit-marketing">
    <div class="easycredit-marketing__grid intro">
        <div class="easycredit-marketing__content">
            <p><?= __('We provide you with a range of marketing components that you can easily activate in your online shop. In this way, you achieve an optimal presentation of financing via easyCredit-Ratenkauf, for higher sales and satisfied customers.') ?></p>
            <h3><?= __('Useful links') ?></h3>
            <ul>
                <li><a href="https://netzkollektiv.com/docs/easycredit-components/" target="_blank"><?= __('Documentation') ?></a></li>
                <li><a href="https://easycredit-demo.netzkollektiv.com/" target="_blank"><?= __('Demo shop with marketing components') ?></a></li>
                <li><a href="https://www.easycredit-ratenkauf.de/marketingmaterial-schulung/" target="_blank"><?= __('Marketing portal') ?></a></li>
            </ul>
        </div>
        <div class="easycredit-marketing__image">
            <div class="img"></div>
        </div>
    </div>
</div>
