<?php if (
    ($block->getConfigValue('marketing/express/express_enabled') && $block->getIsInCatalogProduct()) ||
    ($block->getConfigValue('marketing/express/express_cart_enabled') &&
        ($block->getIsShoppingCart() || (!$block->getIsShoppingCart() && !$block->getIsInCatalogProduct()))
    )
) : ?>
<easycredit-express-button
    webshop-id="<?= /* @noEscape */ $block->getConfigValue('credentials/api_key'); ?>"
    amount="<?= /* @noEscape */ $block->getGrandTotal(); ?>"
    full-width="true" 
    data-mage-init='{
        "Netzkollektiv_EasyCredit/js/view/express": {
            "storeCode": "<?= /* @noEscape */ $block->getStoreCode(); ?>",
            "quoteId": "<?= /* @noEscape */ $block->getQuoteId(); ?>",
            "isInCatalogProduct": "<?= /* @noEscape */ $block->getIsInCatalogProduct(); ?>",
            "isShoppingCart": "<?= /* @noEscape */ $block->getIsShoppingCart(); ?>"
        }
    }'
></easycredit-express-button>
<?php endif; ?>