<?php

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
?>

<dl class="payment-method">
    <p>
        <easycredit-checkout-label><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?></easycredit-checkout-label>  
    </p>
    <p><strong>Transaktions-Nr:</strong> <?php echo $this->escapeHtml($this->getInfo()->getAdditionalInformation('transaction_id')); ?></p>

    <easycredit-checkout payment-plan="<?php echo $block->escapeHtml($block->getPaymentPlan()); ?>"></easycredit-checkout>

</dl>

<?php echo $block->getChildHtml()?>