<?php
/**
 * @var \Netzkollektiv\EasyCredit\Block\PpPlugin $block
 */
?>
<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/modal",
        "mage/translate",
        "domReady!",
        "easycreditWidget"
    ], function ($, modal) {
        $(function() {
            $('.product-info-main .price-box').each(function(){
                var me = this;
                var amount = function() {
                    return $(me).find('*[data-price-type="finalPrice"]').data('price-amount');
                }();

                $(this).rkPaymentPage({
                    webshopId : '<?= $block->escapeHtml($block->getApiKey()); ?>',
                    amount: amount,
                    modal: function(element, content, opts) {
                        var container = '<div class="easycredit-embed-responsive">'+content+'</div>';
                        element.append(container);
                        var modal = $(container).modal({
                            autoOpen:true,
                            innerScroll: false,
                            responsive: true,
                            type: 'popup',
                            title: 'ratenkauf by easyCredit',
                            buttons: []
                        });
                        modal.css('height','700px')
                            .closest('.modal-inner-wrap')
                            .css({'max-width':'700px'});
                    }
                });
            });
        });
    });
</script>
