<?php
/**
 * @var \Netzkollektiv\EasyCredit\Block\Ui\Widget $block
 */
if (!$block->getApiKey()) {
    return;
}
?>
<script>
require([
    "jquery",
    "domReady!",
], function ($) {
    $(function() { 
        $('.product-info-main .price-box').each(function(){
            var me = this;
            var amount = function() {
                return $(me).find('*[data-price-type="finalPrice"]').data('price-amount');
            }();

            var widget = $(['<easycredit-widget', 
                'webshop-id="<?php echo $block->escapeHtml($block->getApiKey()); ?>"',
                'amount="'+amount+'"',
            '/>'].join(' '));
            $(this).append(widget);

            var priceType = 'finalPrice';
            var priceBoxSelector = '.price-box';
            var priceBox = $(priceBoxSelector);
            priceBox.on('priceUpdated', function(event, data) {
                widget.get(0).setAttribute('amount', data[priceType].amount);
            });
        });
    });
});
</script>
