<?php

/**
 * @var \Netzkollektiv\EasyCredit\Block\Ui\Widget $block
 */
if (!$block->getApiKey() || $block->getAmount() === 0) {
    return;
}
?>
<easycredit-widget payment-types="<?= implode(',', $block->getPaymentHelper()->getAvailableMethodTypes()); ?>" webshop-id="<?php echo $block->escapeHtml($block->getApiKey()); ?>" amount="<?php echo $block->getAmount(); ?>" <?= $block->getAdditionalAttributes(); ?>></easycredit-widget>
