<script>
window.ratenkaufbyeasycreditOrderManagementConfig = <?php echo /* @noEscape */ $block->getConfig(); ?>;
</script>
<script type="module" src="https://invoice.easycredit-ratenkauf-webcomponents.pages.dev/easycredit-components/easycredit-components.esm.js"></script>
<script nomodule src="https://invoice.easycredit-ratenkauf-webcomponents.pages.dev/easycredit-components/easycredit-components.js"></script>    