<?php

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>

<dl class="payment-method">
    <dt class="title">
        <easycredit-checkout-label><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?></easycredit-checkout-label>
    </dt>

    <br /><br />
    <strong>Transaktions-Nr:</strong> <?php echo $this->escapeHtml($this->getInfo()->getAdditionalInformation('transaction_id')); ?></p>

    <easycredit-checkout payment-plan="<?php echo $block->escapeHtml($block->getPaymentPlan()); ?>"></easycredit-checkout>
</dl>

<?php echo $block->getChildHtml()?>
