<?php

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>

<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title; ?></dt>
    <strong>Einfach. Fair. In Raten zahlen.</strong><br />

    <?php echo $this->getPaymentPlan(); ?>

    <?php if ($this->getInfo()->getAdditionalInformation('is_captured')) : ?>
    <p><strong>Transaktions-Nr:</strong> <?php echo $this->escapeHtml($this->getInfo()->getAdditionalInformation('transaction_id')); ?></p>
    <?php endif; ?>
</dl>

<?= $block->getChildHtml()?>
