<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>{{pdf_row_separator}}
Einfach. Fair. In Raten zahlen.{{pdf_row_separator}}

<?php if ($specificInfo = $block->getSpecificInformation()) : ?>
    <?php foreach ($specificInfo as $label => $value) : ?>
        <?php echo $block->escapeHtml($label) ?>:
        <?php echo $block->escapeHtml(implode(' ', $block->getValueAsArray($value))) ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif;?>

<?php echo $this->getPaymentPlan(); ?>{{pdf_row_separator}}

<?php echo $block->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())) ?>
