name: Test

on:
  push:
    branches:
    - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        include:
          - magento-version: '2.4.1'
            php-version: 7.4
            composer-version: 'v1'
          - magento-version: '2.4.2'
            php-version: 7.4
            composer-version: 'v1'
          - magento-version: '2.4.3-p3'
            php-version: 7.4
            composer-version: 'v1'
          - magento-version: '2.4.4'
            php-version: 8.1
            composer-version: 'v2'
          - magento-version: '2.4.5'
            php-version: 8.1
            composer-version: 'v2'
          - magento-version: '2.4.6-p2'
            php-version: 8.2
            composer-version: 'v2'
          - magento-version: '2.4.7'
            php-version: 8.3
            composer-version: 'v2'

    name: Magento ${{ matrix.magento-version }}

    env:
      MAGENTO_DIR: /opt/magento/
      PLUGIN_DIR: vendor/teambank/ratenkaufbyeasycredit-plugin-magento-2/

    services:
      mysql:
        image: mysql:8.0.20
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

      elasticsearch:
        image: elasticsearch:7.17.10
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, gd, bcmath, ctype, curl, dom, hash, iconv, intl, openssl, simplexml, soap, xsl, zip, xdebug
          tools: composer:${{ matrix.composer-version }}
      - name: Checkout
        uses: actions/checkout@master
      - name: Debug
        run: |
          php -v
          php -m
          composer -V
          env
          curl http://localhost:9200
      - name: Setup Magento 2
        run: |
          mysql -u root --password=root -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS magento;'
          git clone --depth=1 -b ${{ matrix.magento-version }} https://github.com/magento/magento2 $MAGENTO_DIR
          cd $MAGENTO_DIR
          composer install
          composer require community-engineering/language-de_DE

          # quick patch functional testing framework in subshell
          (
            [ -f $MAGENTO_DIR/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php ] && \
              cd $MAGENTO_DIR/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/ && \
              sed s/xdebug_disable/if\ \(function_exists\(\'debug_disable\'\)\)\ xdebug_disable/g _bootstrap.php > _bootstrap.php1; mv _bootstrap.php1 _bootstrap.php 
          )

          php bin/magento setup:install --base-url=http://localhost/ \
          --db-host=127.0.0.1 --db-name=magento --db-user=root --db-password=root --admin-firstname=Admin \
          --admin-lastname=Istrator --admin-email=admin@magneto.com --admin-user=admin \
          --admin-password=admin1234578! --language=de_DE --currency=EUR --timezone=Europe/Berlin \
          --search-engine=elasticsearch7 --elasticsearch-host=localhost \
          --elasticsearch-port=9200 \
          --backend-frontname=admin

          mysql -u root -proot -h 127.0.0.1 -e "UPDATE admin_user Set interface_locale = 'de_DE';" magento 

          REF=${GITHUB_REF##*/}
          BRANCH=$([[ "$REF" = [0-9]* ]] && echo "$REF-dev" || echo "dev-$REF")
          composer require --ignore-platform-reqs teambank/ratenkaufbyeasycredit-plugin-magento-2 $BRANCH

          php bin/magento s:up
          php bin/magento deploy:mode:set production -s
          php bin/magento s:di:com
          php bin/magento s:static:depl de_DE en_US -j 8

          php bin/magento indexer:set-mode realtime
          php bin/magento config:set admin/usage/enabled 0
          php bin/magento config:set payment/easycredit/credentials/api_key ${{ secrets.EASYCREDITAPIKEY }}
          php bin/magento config:set payment/easycredit/credentials/api_token ${{ secrets.EASYCREDITAPIPASSWORD }}
          php bin/magento config:set payment/easycredit/credentials/api_signature ${{ secrets.EASYCREDITAPISIGNATURE }}

          php bin/magento c:cl

      - name: Static Analyze
        run: |
          cd $MAGENTO_DIR

          composer require phpstan/phpstan bitexpert/phpstan-magento --update-with-all-dependencies

          cd $PLUGIN_DIR
          php $MAGENTO_DIR/vendor/bin/phpstan analyze .
      - name: Coding Style
        run: |
          cd $MAGENTO_DIR
          composer require friendsofphp/php-cs-fixer symplify/easy-coding-standard
          php vendor/bin/ecs check -c $PLUGIN_DIR/ecs.php $PLUGIN_DIR
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Setup Playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps
      - name: Playwright E2E Tests
        run: |
          cd $GITHUB_WORKSPACE
          VERSION=${{ matrix.magento-version }} yarn playwright test -c tests/
      - name: Save Shopware Logs for Debugging
        if: always()
        run: |
          cp -r $MAGENTO_DIR/var/log test-results/${{ matrix.magento-version }}/
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: test-results/
          retention-days: 7
