name: Test

on:
  push:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        include:
          # wontfix for this very old version: "Payment model name is not provided in config"
          #- magento-version: '2.4.1'
          #  php-version: 7.4
          #  composer-version: 'v1'
          #  search-engine: 'elasticsearch7'
          - magento-version: '2.4.2'
            php-version: 7.4
            composer-version: 'v1'
            search-engine: 'elasticsearch7'
          - magento-version: '2.4.3-p3'
            php-version: 7.4
            composer-version: 'v1'
            search-engine: 'elasticsearch7'
          - magento-version: '2.4.4'
            php-version: 8.1
            composer-version: 'v2'
            search-engine: 'elasticsearch7'
          - magento-version: '2.4.5'
            php-version: 8.1
            composer-version: 'v2'
            search-engine: 'elasticsearch7'
          - magento-version: '2.4.6-p2'
            php-version: 8.2
            composer-version: 'v2'
            search-engine: 'elasticsearch7'
          - magento-version: '2.4.7'
            php-version: 8.3
            composer-version: 'v2'
            search-engine: 'elasticsearch7'
          - magento-version: '2.4.8'
            php-version: 8.3
            composer-version: 'v2'
            search-engine: 'elasticsearch8'

    name: Magento ${{ matrix.magento-version }}

    env:
      MAGENTO_DIR: /opt/magento/
      PLUGIN_DIR: vendor/teambank/easycredit-plugin-magento-2/

    services:
      mysql:
        image: mysql:8.0.20
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

      elasticsearch:
        image: elasticsearch:7.17.10
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, gd, bcmath, ctype, curl, dom, hash, iconv, intl, openssl, simplexml, soap, xsl, zip, xdebug
          tools: composer:${{ matrix.composer-version }}
      - name: Checkout
        uses: actions/checkout@master
      - name: Debug
        run: |
          php -v
          php -m
          composer -V
          env
          curl http://localhost:9200
      - name: Setup Magento 2
        run: |
          mysql -u root --password=root -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS magento;'
          git clone --depth=1 -b ${{ matrix.magento-version }} https://github.com/magento/magento2 $MAGENTO_DIR
          cd $MAGENTO_DIR

          composer install || composer install
          composer config minimum-stability dev
          composer config repositories.local path $GITHUB_WORKSPACE
          
          COMPOSER_MIRROR_PATH_REPOS=1 composer require --ignore-platform-reqs teambank/easycredit-plugin-magento-2 dev-${GITHUB_REF##*/}#${GITHUB_SHA}
          composer require community-engineering/language-de_DE
          composer remove magento/composer-dependency-version-audit-plugin

          # quick patch functional testing framework in subshell
          (
            [ -f $MAGENTO_DIR/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php ] && \
              cd $MAGENTO_DIR/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/ && \
              sed s/xdebug_disable/if\ \(function_exists\(\'debug_disable\'\)\)\ xdebug_disable/g _bootstrap.php > _bootstrap.php1; mv _bootstrap.php1 _bootstrap.php 
          )

          php bin/magento setup:install --base-url=http://localhost/ \
          --db-host=127.0.0.1 --db-name=magento --db-user=root --db-password=root --admin-firstname=Admin \
          --admin-lastname=Istrator --admin-email=admin@magneto.com --admin-user=admin \
          --admin-password=admin1234578! --language=de_DE --currency=EUR --timezone=Europe/Berlin \
          --search-engine=${{ matrix.search-engine }} --elasticsearch-host=localhost \
          --elasticsearch-port=9200 \
          --backend-frontname=admin

          mysql -u root -proot -h 127.0.0.1 -e "UPDATE admin_user Set interface_locale = 'de_DE';" magento 

          #REF=${GITHUB_REF##*/}
          #BRANCH=$([[ "$REF" = [0-9]* ]] && echo "$REF-dev" || echo "dev-$REF")
          #composer require --ignore-platform-reqs teambank/easycredit-plugin-magento-2 $BRANCH

          php bin/magento module:disable Magento_AdminAnalytics
          php bin/magento s:up
          php bin/magento deploy:mode:set production -s
          php bin/magento s:di:com
          php bin/magento s:static:depl de_DE en_US -j 8

          php bin/magento indexer:set-mode realtime
          #php bin/magento config:set admin/usage/enabled 0

          php bin/magento config:set customer/address/telephone_show opt

          php bin/magento config:set payment/easycredit/credentials/api_key ${{ secrets.EASYCREDITAPIKEY }}
          php bin/magento config:set payment/easycredit/credentials/api_token ${{ secrets.EASYCREDITAPIPASSWORD }}
          php bin/magento config:set payment/easycredit/credentials/api_signature ${{ secrets.EASYCREDITAPISIGNATURE }}

          php bin/magento c:clean

      - name: Static Analyze
        run: |
          cd $MAGENTO_DIR

          if [[ "${{ matrix.magento-version }}" == "2.4.7" || "${{ matrix.magento-version }}" == "2.4.8" ]]; then
            echo "Using latest PHPStan (2.x) for Magento version ${{ matrix.magento-version }}"
            composer update phpstan/phpstan --with-all-dependencies
            composer require bitexpert/phpstan-magento
          else
            echo "Using specific PHPStan versions for Magento version ${{ matrix.magento-version }}"
            composer require phpstan/phpstan:^1.10 bitexpert/phpstan-magento:^0.30 --update-with-all-dependencies
          fi

          cd $PLUGIN_DIR
          php $MAGENTO_DIR/vendor/bin/phpstan analyze .
      - name: Coding Style
        if: ${{ matrix.magento-version == '2.4.7' }}
        run: |
          cd $MAGENTO_DIR
          composer require friendsofphp/php-cs-fixer symplify/easy-coding-standard --dev
          php vendor/bin/ecs check -c $PLUGIN_DIR/ecs.php $PLUGIN_DIR
      - name: Install Dependencies
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: Setup Playwright
        run: |
          # fixes:  Repository 'https://ppa.launchpadcontent.net/ondrej/php/ubuntu noble InRelease' changed its 'Label' value from '***** The main PPA for supported PHP versions with many PECL extensions *****' to 'PPA for PHP'
          sudo apt-get update -o Acquire::AllowReleaseInfoChange=true 
          yarn playwright install --with-deps chromium
      - name: Playwright E2E Tests
        run: |
          cd $GITHUB_WORKSPACE
          VERSION=${{ matrix.magento-version }} yarn playwright test -c tests/
      - name: Save Magento Logs for Debugging
        if: always()
        run: |
          LOG_DIR=playwright-report/logs
          mkdir $LOG_DIR
          cp -r $MAGENTO_DIR/var/log/* $LOG_DIR/
          for i in $LOG_DIR/*; do
            echo "<a href=\"$(basename $i)\">$i</a><br />" >> $LOG_DIR/index.html
          done;
      - name: Deploy Report
        if: always()
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy playwright-report/ --project-name=easycredit-playwright-reports
